import os
from markdown import markdown
from bs4 import BeautifulSoup

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.lib import colors

EXPORT_DIR = "./exports"
os.makedirs(EXPORT_DIR, exist_ok=True)


def html_to_story(html: str):
    soup = BeautifulSoup(html, "html.parser")
    styles = getSampleStyleSheet()

    # Base style
    normal = ParagraphStyle(
        "NormalCustom",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
        spaceAfter=6,
    )

    h1 = ParagraphStyle(
        "Heading1Custom",
        parent=styles["Heading1"],
        fontSize=20,
        leading=24,
        textColor=colors.darkblue,
        spaceBefore=10,
        spaceAfter=12,
    )

    h2 = ParagraphStyle(
        "Heading2Custom",
        parent=styles["Heading2"],
        fontSize=16,
        leading=20,
        textColor=colors.darkgreen,
        spaceBefore=8,
        spaceAfter=8,
    )

    h3 = ParagraphStyle(
        "Heading3Custom",
        parent=styles["Heading3"],
        fontSize=14,
        leading=18,
        textColor=colors.darkred,
        spaceBefore=6,
        spaceAfter=6,
    )

    code_style = ParagraphStyle(
        "Code",
        parent=normal,
        fontName="Courier",
        fontSize=9,
        leading=11,
        backColor=colors.whitesmoke,
        leftIndent=10,
        rightIndent=10,
        spaceBefore=4,
        spaceAfter=4,
    )

    table_style = ParagraphStyle(
        "Table",
        parent=normal,
        fontName="Courier",
        fontSize=9,
        leading=11,
        leftIndent=10,
    )

    story = []

    # Handle tables manually for nicer mono layout
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows:
            cells = row.find_all(["th", "td"])
            texts = [c.get_text(strip=True) for c in cells]
            if not texts:
                continue
            line = " | ".join(texts)
            story.append(Paragraph(line, table_style))
        story.append(Spacer(1, 0.12 * inch))
        table.decompose()

    # Headings, paragraphs, bullets, code/flowcharts
    for tag in soup.find_all(["h1", "h2", "h3", "p", "li", "pre", "code"]):
        text = tag.get_text().strip()
        if not text:
            continue

        if tag.name == "h1":
            story.append(Paragraph(text, h1))
        elif tag.name == "h2":
            story.append(Paragraph(text, h2))
        elif tag.name == "h3":
            story.append(Paragraph(text, h3))
        elif tag.name == "li":
            story.append(Paragraph("• " + text, normal))
        elif tag.name in ("pre", "code"):
            safe = text.replace(" ", "&nbsp;").replace("\n", "<br/>")
            story.append(Paragraph(safe, code_style))
        elif tag.name == "p":
            story.append(Paragraph(text, normal))

        story.append(Spacer(1, 0.08 * inch))

    return story


def generate_beautiful_pdf(markdown_text: str, filename: str, title: str, subject: str):
    pdf_path = os.path.join(EXPORT_DIR, filename)

    # Markdown → HTML
    html = markdown(markdown_text, extensions=["fenced_code", "tables"])

    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    story = []

    # Title page
    title_style = ParagraphStyle(
        "PDFTitle",
        parent=getSampleStyleSheet()["Title"],
        alignment=TA_CENTER,
        fontSize=28,
        textColor=colors.darkblue,
        spaceAfter=20,
    )

    subtitle_style = ParagraphStyle(
        "PDFSubtitle",
        parent=getSampleStyleSheet()["Normal"],
        alignment=TA_CENTER,
        fontSize=14,
        textColor=colors.black,
        spaceAfter=10,
    )

    footer_style = ParagraphStyle(
        "PDFFooter",
        parent=getSampleStyleSheet()["Normal"],
        alignment=TA_CENTER,
        fontSize=9,
        textColor=colors.grey,
        spaceBefore=200,
    )

    story.append(Paragraph(title, title_style))
    if subject:
        story.append(Paragraph(f"<b>Subject:</b> {subject}", subtitle_style))
    story.append(Paragraph("Generated by Syllabus GPT (HyDE + RAG)", footer_style))
    story.append(PageBreak())

    # Content
    story.extend(html_to_story(html))

    doc.build(story)
    return pdf_path
